name: Codeowner Reviews

# Controls when the workflow will run
on: pull_request_target

jobs:
  assign-users:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Recognizes and assigns reviewers and codeowners
      - name: Auto Reviewers
      - uses: zattoo/reviewers@4.0.1

